export enum OutlineStyleEnum {
    auto = 'auto',
    none = 'none',
    dotted = 'dotted',
    dashed = 'dashed',
    solid = 'solid',
    double = 'double',
    groove = 'groove',
    ridge = 'ridge',
    inset = 'inset',
    outset = 'outset',
    inherit = 'inherit',
    initial = 'initial',
    unset = 'unset',
}
