export enum StyleNameEnum {
    margin = 'margin',
    padding = 'padding',
    display = 'display',
    'flex-direction' = 'flex-direction',
    'align-items' = 'align-items',
    'align-self' = 'align-self',
    'grid-template-columns' = 'grid-template-columns',
    'grid-template-rows' = 'grid-template-rows',
    border = 'border',
    resize = 'resize',
    width = 'witdth',
    height = 'height',
    'font-size' = 'font-size',
}
