export enum UnitsEnum {
    px = 'px',
    em = 'em',
    rem = 'rem',
    vw = 'vw',
    vh = 'vh',
    vmin = 'vmin',
    vmax = 'vmax',
    '%' = '%',
    ex = 'ex',
    ch = 'ch',
    mm = 'mm',
    cm = 'cm',
    in = 'in',
    pt = 'pt',
    pc = 'pc',
}
